### ISSUE TITLE
node.js support

### ISSUE THREAD

**Issue by molefrog** [sloisel/numeric#30]
It would be nice, if numeric.js would have node.js support (require-style loading and npm package). I don't think it's a big deal, because it's browser-independent.

**Comment by mikolalysenko** [comment]
It is already there.  You can just do:

```
 npm install numeric
```

And then:

```
 var numeric = require("numeric")
```

Though I agree it might be nicer to make a more modular library.

**Comment by molefrog** [comment]
That's awesome! Thank you. Maybe I was confused because I couldn't find package.json in repo. Thanks again!
