### ISSUE TITLE
failure to load goog.require('goog.math.Matrix') in benchmark.html

### ISSUE THREAD

**Issue by stepheneb** [sloisel/numeric#7]
Cloned the repo and tried opening the link to the Benchmark page.

Line 73:

```
goog.require('goog.math.Matrix');
```

throws this error:

```
Uncaught ReferenceError: goog is not defined
```

**Comment by sloisel** [comment]
You probably need to run tools/build.sh.

**Comment by stepheneb** [comment]
Thanks for the tip. I also had to install install uglify-js globally.

```
$ npm install uglify-js -g
```

I just learned about https://github.com/notifications ... and am following up on responses to my older comments/issues ;-)
