### ISSUE TITLE
http://www.numericjs.com/ not responding

### ISSUE THREAD

**Issue by stepheneb** [sloisel/numeric#8]
http://www.numericjs.com/ is not responding

Host does not appear to be up:

```
$ ping www.numericjs.com
PING numericjs.com (50.16.208.142): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
--- numericjs.com ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by sloisel** [comment]
I think this is fixed, we'll see when the DNS records propagate.

I tried to update the box using yum a couple of weeks ago and apparently this broke mysql and brought down the whole site. It is perhaps not a good idea to update boxes?
